language: node_js
node_js:
- stable
before_deploy: "echo 'ready?'"
cache:
  directories:
  - node_modules

script:
- npm test
- npm build
deploy:
  provider: azure_web_apps
  slot: myapp-staging
  verbose: true
  on: prod